#!/usr/bin/env python

import os
import sys
sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname(__file__), os.path.pardir)) + "/src")
print(sys.path)

from swarm_controller.SwarmController import SwarmController
from rqt_gui.main import Main


main = Main(filename='swarm_controller')
sys.exit(main.main(standalone='swarm_controller'))
